.TH sparkleshare 1  "August 16, 2010" "version 0.2" "USER COMMANDS"
.SH NAME
sparkleshare \- sharing work made easy
.SH SYNOPSIS
.B sparkleshare
[start|stop|restart|help]
.SH DESCRIPTION
A file sharing system for the desktop that retains a full history of
changes made, and allows work to be sychronized across many systems.
Based on the underlying `git' version control system, sparkleshare is
fast and secure, but the interface is straightforward enough for all
to use.
.SH OPTIONS
.TP
start
Start the sparkleshare system, presenting an introductory dialog if
this is the first time that it has been run.
.TP
stop
Stop sparkleshare, halting all current file sharing and no longer watch
for changes in the configured shares.
.TP
restart
Restart sparkleshare.
.SH RETURN VALUES
Currently sparkleshare only ever returns 0 on exit.
.SH FILES
.TP
~/SparkleShare
Directories set up to be shared are placed under this directory.
.SH BUGS
SparkleShare is currently under development, it is likely that there 
are a number of bugs present in the system. Since the underlying 
file sharing is simply based on `git', even if SparkleShare itself fails,
the data is retrievable in an open format. On-disk corruption is 
extremely unlikely.
