language: csharp
cache:
  directories:
    - upload
jobs:
  # for debugging enable next two lines to allow an os to fail without quitting pipeline
  # allow_failures:
  #   language: csharp

  include:
    - stage: "Compile for Mac"
      os: osx
      before_install:
        - mkdir -p ./upload
        - wget https://dl.xamarin.com/XamarinforMac/Mac/xamarin.mac-3.0.0.393.pkg
        - sudo installer -pkg xamarin.mac*.pkg -target /
      script:
        - msbuild /p:Configuration=ReleaseDist SparkleShare.sln
      before_deploy:
        - zip -r ./SparkleShare/Mac/bin/ReleaseDist/SparkleShare.zip ./SparkleShare/Mac/bin/ReleaseDist/SparkleShare.app
        - cp ./SparkleShare/Mac/bin/ReleaseDist/SparkleShare.zip ./upload/SparkleShare-macos-nightly.zip
      deploy: &deploy_base
        provider: releases
        api_key: ${GITHUB_TOKEN}
        file: ./upload/SparkleShare-macos-nightly.zip
        skip_cleanup: true
        draft: true
        name: Nightly CI Build
        on:
          branch:
            - master
          tags: false

    - stage: "Compile for Linux"
      os: linux
      services:
        - docker
      before_install:
        - mkdir -p ./upload
        - docker pull ubuntu:latest
      script:
        - docker build --file scripts/ci/Dockerfile --tag sparkleshare:nightly .
      before_deploy:
        - export DEPLOY_FILE=`docker run --name container sparkleshare:nightly find / -name sparkleshare*.tar.gz`
      # unfortunately no sparkleshare*.tar.gz will be created by the above commands, so no upload for linux
      # if fixed the tar.gz issue uncomment the following 6 lines to enable upload
      #  - cp ${DEPLOY_FILE} ./upload/SparkleShare-linux-nightly.tar.gz
      # deploy for linux is disabled, because to docker run
      # deploy:
      #     <<: *deploy_base
      #     draft: true
      #     file: ./upload/SparkleShare-linux-nightly.tar.gz

    - stage: "Compile for Windows"
      os: windows
      mono: none
      before_install:
        - mkdir -p ./upload
        # - choco install netfx-4.5.2-devpack
        # - choco install windows-sdk-8.0
        - powershell Install-WindowsFeature Net-Framework-Core
        - choco install -y wixtoolset --version=3.11.2
        - choco install tartool
        - choco install unzip
      script:
        - ./SparkleShare/Windows/build.cmd installer
      before_deploy:
        - mv ./SparkleShare/Windows/SparkleShare.msi  ./upload/SparkleShare-windows-nightly.msi
      deploy:
          <<: *deploy_base
          draft: true
          file: ./upload/SparkleShare-windows-nightly.msi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f1a1178baa78d1162385
    on_success: change
    on_failure: always
    on_start: never
