//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3625
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparkleShare {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Icons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icons() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparkleShare.Icons", typeof(Icons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avatar_default {
            get {
                object obj = ResourceManager.GetObject("avatar_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avatar_default_16 {
            get {
                object obj = ResourceManager.GetObject("avatar_default_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avatar_default_22 {
            get {
                object obj = ResourceManager.GetObject("avatar_default_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avatar_default_24 {
            get {
                object obj = ResourceManager.GetObject("avatar_default_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avatar_default_32 {
            get {
                object obj = ResourceManager.GetObject("avatar_default_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avatar_default_48 {
            get {
                object obj = ResourceManager.GetObject("avatar_default_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dialog_error_16 {
            get {
                object obj = ResourceManager.GetObject("dialog_error_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dialog_error_24 {
            get {
                object obj = ResourceManager.GetObject("dialog_error_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_added_12 {
            get {
                object obj = ResourceManager.GetObject("document_added_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_deleted_12 {
            get {
                object obj = ResourceManager.GetObject("document_deleted_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_edited_12 {
            get {
                object obj = ResourceManager.GetObject("document_edited_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_moved_12 {
            get {
                object obj = ResourceManager.GetObject("document_moved_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_16 {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_22 {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_24 {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_256 {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_32 {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_48 {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap list_point_16 {
            get {
                object obj = ResourceManager.GetObject("list_point_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_syncing_sparkleshare_24 {
            get {
                object obj = ResourceManager.GetObject("process_syncing_sparkleshare_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_syncing_sparkleshare_i_24 {
            get {
                object obj = ResourceManager.GetObject("process_syncing_sparkleshare_i_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_syncing_sparkleshare_ii_24 {
            get {
                object obj = ResourceManager.GetObject("process_syncing_sparkleshare_ii_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_syncing_sparkleshare_iii_24 {
            get {
                object obj = ResourceManager.GetObject("process_syncing_sparkleshare_iii_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_syncing_sparkleshare_iiii_24 {
            get {
                object obj = ResourceManager.GetObject("process_syncing_sparkleshare_iiii_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_syncing_sparkleshare_iiiii_24 {
            get {
                object obj = ResourceManager.GetObject("process_syncing_sparkleshare_iiiii_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_working_22 {
            get {
                object obj = ResourceManager.GetObject("process_working_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap side_splash {
            get {
                object obj = ResourceManager.GetObject("side_splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon sparkleshare {
            get {
                object obj = ResourceManager.GetObject("sparkleshare", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sparkleshare_syncing_error_24 {
            get {
                object obj = ResourceManager.GetObject("sparkleshare_syncing_error_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tutorial_slide_1 {
            get {
                object obj = ResourceManager.GetObject("tutorial_slide_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tutorial_slide_2 {
            get {
                object obj = ResourceManager.GetObject("tutorial_slide_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tutorial_slide_3 {
            get {
                object obj = ResourceManager.GetObject("tutorial_slide_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tutorial_slide_4 {
            get {
                object obj = ResourceManager.GetObject("tutorial_slide_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
