//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4211
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparkleShare {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Icons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparkleShare.Icons", typeof(Icons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap avatar_default {
            get {
                object obj = ResourceManager.GetObject("avatar_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avatar_default_16 {
            get {
                object obj = ResourceManager.GetObject("avatar_default_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avatar_default_22 {
            get {
                object obj = ResourceManager.GetObject("avatar_default_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avatar_default_24 {
            get {
                object obj = ResourceManager.GetObject("avatar_default_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avatar_default_32 {
            get {
                object obj = ResourceManager.GetObject("avatar_default_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avatar_default_48 {
            get {
                object obj = ResourceManager.GetObject("avatar_default_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dialog_error_16 {
            get {
                object obj = ResourceManager.GetObject("dialog_error_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dialog_error_24 {
            get {
                object obj = ResourceManager.GetObject("dialog_error_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_added_12 {
            get {
                object obj = ResourceManager.GetObject("document_added_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_deleted_12 {
            get {
                object obj = ResourceManager.GetObject("document_deleted_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_edited_12 {
            get {
                object obj = ResourceManager.GetObject("document_edited_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_moved_12 {
            get {
                object obj = ResourceManager.GetObject("document_moved_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error_active {
            get {
                object obj = ResourceManager.GetObject("error_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_16 {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_16_mist {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_16_mist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_22 {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_22_mist {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_22_mist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_24 {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_24_mist {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_24_mist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_256 {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_256_mist {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_256_mist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_32 {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_32_mist {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_32_mist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_48 {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_sparkleshare_48_mist {
            get {
                object obj = ResourceManager.GetObject("folder_sparkleshare_48_mist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idle0 {
            get {
                object obj = ResourceManager.GetObject("idle0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idle0_active {
            get {
                object obj = ResourceManager.GetObject("idle0_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idle1 {
            get {
                object obj = ResourceManager.GetObject("idle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idle1_active {
            get {
                object obj = ResourceManager.GetObject("idle1_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idle2 {
            get {
                object obj = ResourceManager.GetObject("idle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idle2_active {
            get {
                object obj = ResourceManager.GetObject("idle2_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idle3 {
            get {
                object obj = ResourceManager.GetObject("idle3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idle3_active {
            get {
                object obj = ResourceManager.GetObject("idle3_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idle4 {
            get {
                object obj = ResourceManager.GetObject("idle4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap idle4_active {
            get {
                object obj = ResourceManager.GetObject("idle4_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_syncing_sparkleshare_24 {
            get {
                object obj = ResourceManager.GetObject("process_syncing_sparkleshare_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_syncing_sparkleshare_24_mist {
            get {
                object obj = ResourceManager.GetObject("process_syncing_sparkleshare_24_mist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_syncing_sparkleshare_i_24 {
            get {
                object obj = ResourceManager.GetObject("process_syncing_sparkleshare_i_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_syncing_sparkleshare_ii_24 {
            get {
                object obj = ResourceManager.GetObject("process_syncing_sparkleshare_ii_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_syncing_sparkleshare_iii_24 {
            get {
                object obj = ResourceManager.GetObject("process_syncing_sparkleshare_iii_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_syncing_sparkleshare_iiii_24 {
            get {
                object obj = ResourceManager.GetObject("process_syncing_sparkleshare_iiii_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_syncing_sparkleshare_iiiii_24 {
            get {
                object obj = ResourceManager.GetObject("process_syncing_sparkleshare_iiiii_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_working_22 {
            get {
                object obj = ResourceManager.GetObject("process_working_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap side_splash {
            get {
                object obj = ResourceManager.GetObject("side_splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon sparkleshare {
            get {
                object obj = ResourceManager.GetObject("sparkleshare", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sparkleshare_syncing_error_24 {
            get {
                object obj = ResourceManager.GetObject("sparkleshare_syncing_error_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
