//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparkleShare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparkleShare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&apos;day-entry&apos;&gt;
        ///    &lt;div class=&apos;day-entry-header&apos;&gt;
        ///        &lt;!-- $day-entry-header --&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&apos;day-entry-content&apos;&gt;
        ///        &lt;!-- $day-entry-content --&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string day_entry_html {
            get {
                return ResourceManager.GetString("day_entry_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&apos;event-entry&apos; style=&apos;background-image: url(&quot;&lt;!-- $event-avatar-url --&gt;&quot;);&apos;&gt;
        ///    &lt;div class=&apos;event-user-name&apos;&gt;&lt;!-- $event-user-name --&gt;&lt;/div&gt;
        ///    &lt;div class=&apos;event-folder&apos;&gt;&lt;!-- $event-folder --&gt;&lt;/div&gt;
        ///
        ///    &lt;!-- $event-entry-content --&gt;
        ///
        ///    &lt;div class=&quot;clearer&quot;&gt;&lt;/div&gt;
        ///    &lt;div class=&quot;event-timestamp&quot;&gt;&lt;!-- $event-time --&gt;&lt;/div&gt;
        ///    &lt;div class=&quot;action note&quot;&gt;Add note&lt;/div&gt;
        ///    &lt;div class=&quot;action show&quot;&gt;Show all&lt;/div&gt;
        ///
        ///    &lt;div class=&quot;clearer&quot;&gt;&lt;/div&gt;
        ///
        ///    &lt;div class=&quot;comments-section&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string event_entry_html {
            get {
                return ResourceManager.GetString("event_entry_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;SparkleShare Event Log&lt;/title&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;&lt;!-- $jquery-url --&gt;&quot;&gt;&lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot;&gt;
        ///          $(document).ready(function () {
        ///              $(&apos;.comments-section&apos;).each (function () {
        ///                if ($(this).find (&apos;.comments&apos;).children ().size () &lt; 1) {
        ///                  $(this).hide ();
        ///                }
        ///              });
        ///
        ///              $(&apos;.buddy-icon&apos;).each (function () {
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string event_log_html {
            get {
                return ResourceManager.GetString("event_log_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.6.1
        /// * http://jquery.com/
        /// *
        /// * Copyright 2011, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2011, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// *
        /// * Date: Thu May 12 15:04:36 2011 -0400
        /// */
        ///(function(a,b){function cy(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cv(a){if(!cj[a]){var [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_js {
            get {
                return ResourceManager.GetString("jquery_js", resourceCulture);
            }
        }
    }
}
